const adjective: string[] = [
  "happy", "advanced", "friendly", "technical", "unique", "creative", "innovative", "efficient", "reliable", "powerful",
  "flexible", "intuitive", "secure", "robust", "scalable", "dynamic", "interactive", "responsive", "intelligent", "automated",
  "optimized", "customizable", "adaptable", "versatile", "comprehensive", "integrated", "streamlined", "sophisticated", "seamless",
  "collaborative", "productive", "agile", "effective", "convenient", "userfriendly", "practical", "durable", "economical",
  "sustainable", "ergonomic", "portable", "compact", "sleek", "stylish", "elegant", "modern", "classic", "trendy", "fashionable",
  "chic", "luxurious", "comfortable", "cozy", "spacious", "organized", "clean", "tidy", "neat", "orderly", "systematic", "logical",
  "analytical", "strategic", "tactical", "groundbreaking", "revolutionary", "visionary", "futuristic", "cuttingedge", "stateoftheart",
  "progressive", "forwardthinking", "pioneering", "trailblazing", "adventurous", "daring", "bold", "courageous", "fearless", "brave",
  "valiant", "heroic", "gallant", "intrepid", "confident", "assured", "selfassured", "poised", "composed", "calm", "serene",
  "peaceful", "tranquil", "relaxed", "mellow", "laidback", "easygoing", "carefree", "cheerful", "joyful", "jubilant", "ecstatic",
  "elated", "exuberant", "enthusiastic", "excited", "passionate", "zealous", "fervent", "ardent", "devoted", "dedicated", "committed",
  "loyal", "faithful", "trustworthy", "honest", "sincere", "genuine", "authentic", "real", "true", "legitimate", "valid", "sound",
  "solid", "stable", "steady", "constant", "consistent", "dependable", "trusty", "unfailing", "steadfast", "unwavering", "resolute",
  "determined", "persistent", "tenacious", "persevering", "resilient", "tough", "strong", "mighty", "forceful", "vigorous", "energetic",
  "lively", "vivacious", "spirited", "buoyant", "bouncy", "perky", "chipper", "peppy", "zippy", "zesty", "spicy", "tangy", "flavorful",
  "tasty", "delicious", "savory", "appetizing", "mouthwatering", "delectable", "scrumptious", "yummy", "delightful", "pleasant", "pleasing",
  "agreeable", "likable", "lovable", "adorable", "charming", "enchanting", "captivating", "alluring", "attractive", "beautiful", "gorgeous",
  "stunning", "striking", "dazzling", "brilliant", "radiant", "glowing", "luminous", "shimmering", "gleaming", "glistening", "sparkling",
  "twinkling", "glittering", "shining", "bright", "vivid", "colorful", "vibrant", "rich", "lush", "luxuriant", "abundant", "plentiful",
  "copious", "ample", "bountiful", "generous", "liberal", "lavish", "extravagant", "opulent", "sumptuous", "magnificent", "grand", "splendid",
  "majestic", "regal", "royal", "noble", "dignified", "distinguished", "eminent", "illustrious", "renowned", "famous", "celebrated", "acclaimed",
  "esteemed", "respected", "revered", "venerated", "honored", "admired", "cherished", "treasured", "prized", "valued", "precious", "priceless",
  "invaluable", "irreplaceable", "singular", "distinct", "special", "exceptional", "extraordinary", "remarkable", "outstanding", "superb",
  "excellent", "superior", "supreme", "paramount", "preeminent", "foremost", "leading", "top", "prime", "chief", "principal", "main", "major",
  "key", "central", "vital", "essential", "crucial", "critical", "important", "significant", "momentous", "consequential", "weighty", "serious",
  "grave", "solemn", "earnest", "intense", "profound", "deep", "meaningful", "substantial", "considerable", "extensive", "thorough", "complete",
  "full", "whole", "entire", "total", "absolute", "utter", "sheer", "pure", "perfect", "ideal", "exemplary", "model", "quintessential",
  "archetypal", "classic", "typical", "standard", "normal", "regular", "usual", "ordinary", "common", "conventional", "traditional", "customary",
  "familiar", "routine", "everyday", "mundane", "prosaic", "plain", "simple", "basic", "fundamental", "elementary", "rudimentary", "primary",
  "initial", "original", "first", "earliest", "primitive", "ancient", "old", "antique", "vintage", "retro", "nostalgic", "sentimental",
  "emotional", "sensitive", "tender", "gentle", "mild", "soft", "light", "delicate", "subtle", "nuanced", "fine", "precise", "exact",
  "accurate", "correct", "proper", "appropriate", "suitable", "fitting", "apt", "relevant", "pertinent", "applicable", "germane",
  "specific", "particular", "distinctive", "characteristic", "typical", "representative", "indicative", "symptomatic", "suggestive",
  "expressive", "revealing", "telling", "meaningful", "pregnant", "loaded", "charged", "potent", "cogent", "compelling", "persuasive",
  "convincing", "credible", "plausible", "likely", "probable", "feasible", "viable", "workable", "practical", "pragmatic", "realistic",
  "sensible", "reasonable", "rational", "logical", "coherent", "intelligible", "comprehensible", "understandable", "clear", "lucid",
  "plain", "straightforward", "direct", "explicit", "unambiguous", "unequivocal", "definite", "certain", "sure", "positive", "assertive",
  "emphatic", "categorical", "unqualified", "unconditional", "inclusive", "all encompassing", "universal", "global", "worldwide",
  "international", "cosmopolitan", "multicultural", "diverse", "varied", "assorted", "mixed", "heterogeneous", "eclectic", "multifaceted",
  "complex", "complicated", "intricate", "involved", "elaborate", "developed", "evolved", "refined", "polished", "cultured", "cultivated",
  "educated", "learned", "erudite", "scholarly", "academic", "intellectual", "cerebral", "cognitive", "mental", "psychological", "spiritual",
  "mystical", "ethereal", "celestial", "divine", "heavenly", "sublime", "transcendent", "lofty", "elevated", "exalted", "virtuous",
  "righteous", "moral", "ethical", "principled", "upright", "honorable", "respectable", "reputable", "estimable", "worthy", "deserving",
  "meritorious"
];

const noun: string[] = [
  "blockchain", "cryptocurrency", "token", "transaction", "contract", "DeFi", "NFT", "stake", "validator", "cluster",
  "epoch", "slot", "block", "hash", "signature", "publickey", "privatekey", "address", "account", "balance",
  "lamport", "wrapped", "bridge", "swap", "liquidity", "yield", "farming", "staking", "governance", "DAO",
  "vote", "proposal", "escrow", "multisig", "airdrop", "Merkle", "proof", "consensus", "network", "node",
  "RPC", "API", "SDK", "CLI", "explorer", "dApp", "protocol", "ecosystem", "mainnet", "testnet",
  "devnet", "exchange", "market", "orderbook", "AMM", "DEX", "CEX", "lending", "borrowing", "collateral",
  "liquidation", "oracle", "pricefeed", "program", "instruction", "compiler", "runtime", "bytecode", "gas", "fee",
  "rent", "storage", "compute", "bandwidth", "latency", "throughput", "TPS", "finality", "sharding", "scaling",
  "Layer1", "Layer2", "rollup", "sidechain", "interoperability", "tokenization", "mint", "burn", "supply", "circulation",
  "marketcap", "volume", "depth", "spread", "slippage", "arbitrage", "APY", "APR", "compounding", "rebase",
  "algorithmic", "stablecoin", "pegged", "synthetic", "derivative", "future", "option", "perpetual", "leverage", "margin",
  "long", "short", "hedge", "risk", "volatility", "index", "ETF", "HODL", "FOMO", "ATH",
  "ATL", "pump", "bull", "bear", "whale", "ICO", "IDO", "IEO", "STO", "launchpad",
  "vesting", "lockup", "tokenomics", "emission", "inflation", "deflation", "buyback", "delegation", "nominator", "slashing",
  "rewards", "commission", "quorum", "majority", "veto", "snapshot", "proxy", "reputation", "identity", "KYC",
  "AML", "compliance", "regulation", "license", "audit", "security", "privacy", "encryption", "decryption", "ZK",
  "SNARK", "STARK", "bulletproof", "homomorphic", "MPC", "TEE", "enclave", "seed", "mnemonic", "recovery",
  "user", "client", "server", "frontend", "backend", "fullstack", "REST", "P2P", "mesh", "topology",
  "routing", "gossip", "tower", "turbine", "archivers", "replicator", "leader", "follower", "fisherman", "keeper",
  "liquidator", "arbitrageur", "marketmaker", "taker", "maker", "bid", "ask", "momentum", "trend", "resistance",
  "support", "Fibonacci", "Elliot", "Wyckoff", "Dow", "Ichimoku", "RSI", "MACD", "Bollinger", "parabolic",
  "SAR", "indicator", "oscillator", "divergence", "convergence", "breakout", "breakdown", "channel", "wedge", "triangle",
  "flag", "pennant", "head", "shoulders", "doubletop", "doublebottom", "cup", "handle", "gap", "island",
  "reversal", "continuation", "accumulation", "distribution", "consolidation", "retracement", "extension", "pivot", "trendline", "Gann",
  "harmonic", "wave", "cycle", "timeframe", "tick", "candlestick", "bar", "line", "pointandfigure", "Kagi",
  "Renko", "HeikinAshi", "marketprofile", "volumeprofile", "orderflow", "Level2", "tape", "timesales", "marketdepth", "float",
  "outstanding", "restricted", "unrestricted", "offering", "placement", "shelf", "prospectus", "filing", "registration", "exemption",
  "accredited", "qualified", "institutional", "retail", "OTC", "pinksheet", "bulletin", "board", "listing", "delisting",
  "IPO", "direct", "SPAC", "merger", "acquisition", "takeover", "tender", "spinoff", "divestiture", "restructuring",
  "receivership", "administrator", "creditor", "debtor", "asset", "liability", "equity", "debt", "bond", "note",
  "debenture", "convertible", "warrant", "put", "call", "strike", "expiry", "premium", "intrinsic", "extrinsic",
  "theta", "delta", "gamma", "vega", "rho", "implied", "historical", "skew", "kurtosis", "normal",
  "lognormal", "distribution", "mean", "median", "mode", "standard", "deviation", "variance", "covariance", "correlation",
  "regression", "factor", "alpha", "beta", "Sharpe", "Sortino", "Treynor", "Jensen", "CAPM", "value",
  "growth", "size", "quality", "anomaly", "efficient", "hypothesis", "random", "walk", "behavioral", "prospect",
  "theory", "utility", "aversion", "seeking", "neutral", "tolerance", "capacity", "appetite", "budgeting", "forecasting",
  "projection", "modeling", "simulation", "optimization", "linear", "nonlinear", "stochastic", "MonteCarlo", "sensitivity", "scenario",
  "stress", "test", "backtesting", "forwardtesting", "papertrading", "live", "demo", "sandbox", "production", "staging",
  "development", "assurance", "control", "management", "committee", "executive", "specialist", "consultant", "strategist", "advisor",
  "planner", "researcher", "scientist", "engineer", "developer", "architect", "designer", "product", "project", "program",
  "resource", "talent", "skill", "competency", "capability", "knowledge", "expertise", "experience", "qualification", "certification",
  "accreditation", "license", "credential", "degree", "diploma", "certificate", "training", "education", "learning", "development",
  "growth", "innovation", "creativity", "ideation", "brainstorming", "problemsolving", "decisionmaking", "criticalthinking", "analyticalthinking", "systemsthinking",
  "strategicthinking", "vision", "mission", "goal", "objective", "strategy", "tactic", "plan", "roadmap", "milestone",
  "deliverable", "outcome", "output", "input", "process", "procedure", "policy", "standard", "guideline", "framework",
  "methodology", "paradigm", "approach", "technique", "tool", "technology", "system", "platform", "infrastructure", "architecture",
  "design", "pattern", "blueprint", "prototype", "iteration", "sprint", "agile", "scrum", "kanban", "lean",
  "SixSigma", "Kaizen", "continuous", "improvement", "efficiency", "effectiveness", "productivity", "performance", "metric", "KPI",
  "benchmark", "baseline", "target", "threshold", "SLA", "dashboard", "scorecard", "report", "analytics", "insight",
  "intelligence", "data", "information", "knowledge", "wisdom", "algorithm", "heuristic", "neuralnetwork", "machinelearning", "deeplearning",
  "AI", "LLM", "robotics", "automation", "IoT", "BigData", "cloud", "edge", "fog", "quantum",
  "nanotechnology", "biotechnology", "augmented", "virtual", "mixed", "reality", "gamification", "digitization", "transformation", "disruption",
  "cryptography", "hashrate", "wallet", "coldwallet", "hotwallet", "ledger", "fork", "halving", "mining", "PoW",
  "PoS", "DPoS", "Sybil", "mempool", "nonce", "Satoshi", "fiat", "altcoin", "coin", "whitepaper",
  "roadmap", "presale", "bounty", "orderbook", "limit", "market", "stop", "trailing", "futures", "options",
  "plasma", "state", "channel", "sharding", "PBFT", "Raft", "Byzantine", "privacy", "mixers", "tumblers",
  "ring", "stealth", "confidential", "threshold", "utility", "security", "commodity", "elastic", "bonding", "curve",
  "pool", "vault", "farm", "harvest", "impermanent", "flash", "loan", "sandwich", "frontrunning", "backrunning",
  "MEV", "signature", "Schnorr", "BLS", "ECDSA", "RSA", "SHA256", "Blake2"
];

const product: string[] = [
  "fund", "reserve", "coffer", "pool", "cache", "stockpile", "warchest", "nestegg", "product",
  "offering", "goods", "merchandise", "commodity", "item", "article", "ware", "creation", "vault", "safe", "strongroom",
  "chamber", "crypt", "cellar", "repository", "depository", "stronghold", "treasury", "exchequer", "purse", "bank",
  "coffer", "finance", "asset", "reserve", "wallet", "billfold", "pocketbook", "purse", "handbag", "cardholder", "account",
  "record", "ledger", "books", "tally", "chest", "locker", "box", "container", "capsule", "portfolio", "basket", "collection",
  "assortment", "bundle", "package", "kit", "set", "suite", "array", "inventory", "stock", "supply", "store", "hoard", "accumulation",
  "aggregation", "compilation", "compendium", "treasury", "thesaurus", "archive", "library", "repository", "database", "warehouse",
  "storehouse", "depot", "hub", "center", "nexus", "core", "heart", "nucleus", "foundation", "base", "cornerstone", "pillar",
  "mainstay", "backbone", "linchpin", "keystone", "fulcrum", "pivot", "axis", "source", "wellspring", "fount", "origin",
  "genesis", "root", "seed", "kernel", "catalyst", "spark", "trigger", "impetus", "stimulus", "spur", "incentive", "drive",
  "force", "power", "energy", "essence", "soul", "spirit", "quintessence", "crux", "substance", "nub", "nitty", "gritty",
  "alpha", "omega", "bedrock", "bulwark", "citadel", "fortress", "bastion", "redoubt", "sanctuary", "haven", "refuge",
  "shelter", "harbor", "port", "anchorage", "dock", "jetty", "pier", "wharf", "landing", "platform", "stage", "podium",
  "rostrum", "pulpit", "soapbox", "stump", "forum", "arena", "coliseum", "stadium", "amphitheater", "theater", "auditorium",
  "hall", "chamber", "court", "tribunal", "bench", "bar", "dock", "stand", "witness", "box", "jury", "panel", "board", "committee",
  "council", "cabinet", "ministry", "department", "bureau", "office", "agency", "institution", "establishment", "organization",
  "corporation", "company", "firm", "enterprise", "venture", "undertaking", "endeavor", "project", "operation", "mission",
  "campaign", "crusade", "push", "thrust", "initiative", "movement", "bandwagon", "juggernaut", "steamroller", "behemoth", "titan",
  "colossus", "giant", "goliath", "leviathan", "mammoth", "monster", "powerhouse", "dynamo", "locomotive", "engine", "motor",
  "machine", "mechanism", "apparatus", "device", "gadget", "gizmo", "contraption", "appliance", "tool", "implement", "instrument",
  "utensil", "accessory", "attachment", "adjunct", "auxiliary", "subsidiary", "complement", "supplement", "addition", "addendum",
  "appendix", "appendage", "offshoot", "outgrowth", "ramification", "branch", "arm", "wing", "projection", "extension",
  "protrusion", "prominence", "protuberance", "node", "vertex", "apex", "pinnacle", "zenith", "acme", "climax", "culmination",
  "capstone", "crowning", "consummation"
];

export const ProductNameGen = (): string => {
  const getRandomWord = (array: string[]): string => {
    return array[Math.floor(Math.random() * array.length)];
  };

  const capitalizeFirstLetter = (string: string): string => {
    return string.charAt(0).toUpperCase() + string.slice(1);
  };

  const a = capitalizeFirstLetter(getRandomWord(adjective));
  const n = capitalizeFirstLetter(getRandomWord(noun));
  const p = capitalizeFirstLetter(getRandomWord(product));

  return `${a}${n}${p}`;
};
