export const DRIFT_ORDER_TYPES: [string, ...string[]] = [
  "Market",
  "Limit",
  // "Trigger Market",
  // "Trigger Limit",
  // "Oracle",
];

export const DRIFT_PERP_MARKETS: [string, ...string[]] = [
  "SOL-PERP",
  "BTC-PERP",
  "ETH-PERP",
  "APT-PERP",
  "1MBONK-PERP",
  "MATIC-PERP",
  "ARB-PERP",
  "DOGE-PERP",
  "BNB-PERP",
  "SUI-PERP",
  "1MPEPE-PERP",
  "OP-PERP",
  "RENDER-PERP",
  "XRP-PERP",
  "HNT-PERP",
  "INJ-PERP",
  "LINK-PERP",
  "RLB-PERP",
  "PYTH-PERP",
  "TIA-PERP",
  "JTO-PERP",
  "SEI-PERP",
  "AVAX-PERP",
  "WIF-PERP",
  "JUP-PERP",
  "DYM-PERP",
  "TAO-PERP",
  "W-PERP",
  "KMNO-PERP",
  "TNSR-PERP",
  "DRIFT-PERP",
  "CLOUD-PERP",
  "IO-PERP",
  "ZEX-PERP",
  "POPCAT-PERP",
  "1KWEN-PERP",
  // "TRUMP-WIN-2024-BET",
  // "KAMALA-POPULAR-VOTE-2024-BET",
  // "FED-CUT-50-SEPT-2024-BET",
  // "REPUBLICAN-POPULAR-AND-WIN-BET",
  // "BREAKPOINT-IGGYERIC-BET",
  // "DEMOCRATS-WIN-MICHIGAN-BET",
  // "TON-PERP",
  // "LANDO-F1-SGP-WIN-BET",
  // "MOTHER-PERP",
  // "MOODENG-PERP",
  // "WARWICK-FIGHT-WIN-BET",
];

export const DRIFT_SPOT_MARKETS: [string, ...string[]] = [
  "SOL/USDC",
  "mSOL/USDC",
  "wBTC/USDC",
  "wETH/USDC",
  "USDT/USDC",
  "jitoSOL/USDC",
  "PYTH/USDC",
  "bSOL/USDC",
  "JTO/USDC",
  "WIF/USDC",
  "JUP/USDC",
  "RENDER/USDC",
  "W/USDC",
  "TNSR/USDC",
  "DRIFT/USDC",
  "INF/USDC",
  "dSOL/USDC",
  "USDY/USDC",
  "JLP/USDC",
  "POPCAT/USDC",
  "CLOUD/USDC",
  "PYUSD/USDC",
  "USDe/USDC",
  "sUSDe/USDC",
  "BNSOL/USDC",
  "MOTHER/USDC",
];
