[workspace]
members = ["programs/*"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = "0.29.0"
solana-program = "=1.18.12"

anchor-gen = "0.3.1"
spl-token = "=4.0.1"
spl-token-2022 = "3.0.2"
spl-associated-token-account = "3.0.2"
spl-token-metadata-interface = "0.3.3"
spl-transfer-hook-interface = "0.6.3"
pyth-sdk-solana = "0.10.1"
strum = { version = "0.26", features = ["derive"] }

drift = { path = "./deps/drift" }
marinade = { path = "./deps/marinade" }
