[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
anchor-lang = { version="0.30.0", features=["init-if-needed"] }
anchor-attribute-account = "0.30.0"
anchor-spl = "0.30.0"
solana-program = "=1.18.11"

anchor-gen = "0.3.1"
flatbuffers = "24.3.25"
spl-token-2022 = "3.0.2"
spl-token-metadata-interface = "0.3.3"
spl-transfer-hook-interface = "0.6.3"
pyth-sdk-solana = "0.10.1"

drift = { path="./deps/drift" }

[patch.crates-io]
anchor-attribute-account = { path="./deps/anchor-attribute-account" }
