#
# Drift
#
drift:
  - ix_name: initializeUserStats
    permission: DriftInitialize
    integration: Drift
    vault_aliases: ["authority"]
    signed_by_vault: true
  - ix_name: initializeUser
    permission: DriftInitialize
    integration: Drift
    vault_aliases: ["authority"]
    signed_by_vault: true
  - ix_name: deleteUser
    permission: DriftDeleteUser
    integration: Drift
    vault_aliases: ["authority"]
    signed_by_vault: true
    mutable_vault: true
  - ix_name: updateUserDelegate
    permission: DriftUpdateUser
    integration: Drift
    vault_aliases: ["authority"]
    accounts_struct: UpdateUser
    signed_by_vault: true
  - ix_name: updateUserCustomMarginRatio
    permission: DriftUpdateUser
    integration: Drift
    vault_aliases: ["authority"]
    accounts_struct: UpdateUser
    signed_by_vault: true
  - ix_name: updateUserMarginTradingEnabled
    permission: DriftUpdateUser
    integration: Drift
    vault_aliases: ["authority"]
    accounts_struct: UpdateUser
    signed_by_vault: true
  - ix_name: deposit
    permission: DriftDeposit
    integration: Drift
    vault_aliases: ["authority"]
    with_remaining_accounts: true
    signed_by_vault: true
    mutable_vault: true
  - ix_name: withdraw
    permission: DriftWithdraw
    integration: Drift
    vault_aliases: ["authority"]
    with_remaining_accounts: true
    signed_by_vault: true
    mutable_vault: true
  - ix_name: placeOrders
    permission: DriftPlaceOrders
    integration: Drift
    vault_aliases: ["authority"]
    with_remaining_accounts: true
    signed_by_vault: true
    mutable_vault: true
  - ix_name: cancelOrders
    permission: DriftCancelOrders
    integration: Drift
    vault_aliases: ["authority"]
    with_remaining_accounts: true
    signed_by_vault: true
  - ix_name: cancelOrdersByIds
    permission: DriftCancelOrders
    integration: Drift
    vault_aliases: ["authority"]
    accounts_struct: CancelOrders
    with_remaining_accounts: true
    signed_by_vault: true
  - ix_name: modifyOrder
    permission: DriftModifyOrders
    integration: Drift
    vault_aliases: ["authority"]
    signed_by_vault: true

#
# Kamino Lending
#
kamino_lending:
  - ix_name: initUserMetadata
    permission: KaminoInit
    integration: KaminoLending
    vault_aliases: ["owner"]
    signed_by_vault: true
  - ix_name: initObligation
    permission: KaminoInit
    integration: KaminoLending
    vault_aliases: ["obligation_owner"]
    signed_by_vault: true
  - ix_name: initObligationFarmsForReserve
    permission: KaminoInit
    integration: KaminoLending
    vault_aliases: ["owner"]
    signed_by_vault: true
  - ix_name: depositReserveLiquidityAndObligationCollateral
    permission: KaminoDeposit
    integration: KaminoLending
    vault_aliases: ["owner"]
    signed_by_vault: true

#
# Jupiter Governance and Vote
#
jupiter_gov:
  - ix_name: newVote
    permission: VoteOnProposal
    integration: JupiterVote
    signed_by_vault: true

jupiter_vote:
  - ix_name: newEscrow
    permission: StakeJup
    integration: JupiterVote
    vault_aliases: ["escrow_owner"]
    signed_by_vault: true
  - ix_name: increaseLockedAmount
    permission: VoteOnProposal
    integration: JupiterVote
    # https://github.com/glamsystems/glam/pull/402
    vault_aliases: ["payer"]
    signed_by_vault: true
    mutable_vault: true # vault is fee payer
  - ix_name: openPartialUnstaking
    permission: UnstakeJup
    integration: JupiterVote
    vault_aliases: ["owner"]
    signed_by_vault: true
  - ix_name: mergePartialUnstaking
    permission: UnstakeJup
    integration: JupiterVote
    vault_aliases: ["owner"]
    signed_by_vault: true
  - ix_name: withdraw
    permission: UnstakeJup
    integration: JupiterVote
    vault_aliases: ["escrow_owner", "payer"]
    signed_by_vault: true
    mutable_vault: true # vault is fee payer
  - ix_name: withdrawPartialUnstaking
    permission: UnstakeJup
    integration: JupiterVote
    vault_aliases: ["owner", "payer"]
    signed_by_vault: true
    mutable_vault: true # vault is fee payer
  - ix_name: toggleMaxLock
    permission: UnstakeJup
    integration: JupiterVote
    vault_aliases: ["escrow_owner"]
    signed_by_vault: true
  - ix_name: castVote
    permission: VoteOnProposal
    integration: JupiterVote
    vault_aliases: ["vote_delegate"]
    signed_by_vault: true

#
# Marinade
#

marinade:
  - ix_name: deposit
    permission: Stake
    integration: Marinade
    vault_aliases: ["transfer_from"]
    signed_by_vault: true
    mutable_vault: true
  - ix_name: liquidUnstake
    permission: Unstake
    integration: Marinade
    vault_aliases: ["transfer_sol_to", "get_msol_from_authority"]
    signed_by_vault: true
    mutable_vault: true
  - ix_name: claim
    permission: Unstake
    integration: Marinade
    vault_aliases: ["transfer_sol_to"]
    signed_by_vault: true
    with_remaining_accounts: true
    mutable_vault: true
    mutable_state: true
  - ix_name: orderUnstake
    permission: Unstake
    integration: Marinade
    vault_aliases: ["burn_msol_authority"]
    signed_by_vault: true
    mutable_vault: true
    mutable_state: true
  - ix_name: depositStakeAccount
    permission: Stake
    integration: Marinade
    vault_aliases: ["stake_authority", "rent_payer"]
    signed_by_vault: true
    mutable_vault: true
    mutable_state: true
