name: List services in GCP
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v0.3.1"
        with:
          create_credentials_file: "true"
          workload_identity_provider: "https://iam.googleapis.com/projects/639940077006/locations/global/workloadIdentityPools/github-workflow/providers/github"
          service_account: "glam-api-419002@appspot.gserviceaccount.com"
      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud config set project glam-api-419002
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud services list
